### ISSUE TITLE
Consumer key and consumer secrets doesn't work

### ISSUE THREAD

**Issue by f-liva** [viagogo/gogokit.php#1]
I have a working key pair for my consumer, but these don't work more with this official PHP interface. What is client id and client secret and where I have to find them?

**Comment by akilb** [comment]
Hey Federico,

My guess is that your credentials are for the previous version of the viagogo API. GogoKit is a library for the new V2 API (see the docs here http://viagogo.github.io/developer.viagogo.net/) and you will need new credentials for this API. You can reach out to your viagogo affiliate manager to get access to the new API.

Hope this helps!

**Comment by f-liva** [comment]
I've obtained the new key pairs for the new APIs. It works fine, thank you.
