### ISSUE TITLE
CLIENT_ID and CLIENT_SECRET

### ISSUE THREAD

**Issue by jaysnanavati** [viagogo/gogokit.php#5]
How do I get the clientid and the clientSecret , there is no documentation for this on: http://developer.viagogo.net ? 

Thanks,
Jay

**Comment by akilb** [comment]
Hi @jaysnanavati,

Sorry for the delay. You can contact the viagogo Affiliates team (affiliate@viagogo.com) to get set up with a client ID and secret.

Thanks,
Akil
