### ISSUE TITLE
how can i get all events in specific venue?

### ISSUE THREAD

**Issue by VolodymyrMordas** [viagogo/gogokit.php#6]
according to viagogo-docs (http://goo.gl/hTFj2Y) I can get all events in specific venue using link like this - https://api.viagogo.net/v2/categories/0/events?venue_id=1364?page=2&page_size=1.

but, the result of it request are events in all venues

{
    "total_items":53432,
    "page":1,
    "page_size":10,
    "_links":{
        "self":{
            "href":"https:\/\/api.viagogo.net\/v2\/categories\/0\/events?venue_id=1364&page=1&page_size=10&tagTypeId=1",
            "title":null,
            "templated":false
        },
        "last":{
            "href":"https:\/\/api.viagogo.net\/v2\/categories\/0\/events?venue_id=1364&page=5344&page_size=10&tagTypeId=1",
            "title":null,
            "templated":false
        },
        "next":{
            "href":"https:\/\/api.viagogo.net\/v2\/categories\/0\/events?venue_id=1364&page=2&page_size=10&tagTypeId=1",
            "title":null,
            "templated":false
        }
    },
    "_embedded":{
        "items":[
            {
                "id":880821,
                "name":"Expo 2015 - Milan - Open Date",
                "start_date":"2015-05-01T09:00:00+02:00",
                "end_date":"2015-10-31T23:00:00+01:00",
                "on_sale_date":"2015-02-25T15:00:00+01:00",
                "date_confirmed":true,
                "min_ticket_price":{
                    "amount":10.2997,
                    "currency_code":"GBP",
                    "display":"\u00a310.30"
                },
                "notes_html":"<div class=\"v-box-pri v-in-18 v-padt-9 v-padb-12\">\n\t\n\t<ul class=\"ul mb0\">\n\t<li>All sales are final<\/li>\n\n<li>Age restrictions may apply, please check with the venue for more details<\/li>\n<li>Event dates and times are subject to change, it is up to you to check local listings for updates<\/li>\n<li>After your purchase, you will receive a confirmation email with your ticket delivery details and timing<\/li>\n\t<\/ul>\t\n<\/div>",
                "restrictions_html":"Please note these are flexible tickets with no fixed date. Access to the event is subject to venue capacity on the day. If the venue is full, access will be denied so please ensure you arrive in good time.",
                "affiliate_commission_tier":"Normal",
                "_links":{
                    "self":{
                        "href":"https:\/\/api.viagogo.net\/v2\/events\/880821?category_id=33700",
                        "title":null,
                        "templated":false
                    },
                    "event:category":{
                        "href":"https:\/\/api.viagogo.net\/v2\/categories\/33700",
                        "title":null,
                        "templated":false
                    },
                    "event:listingconstraints":{
                        "href":"https:\/\/api.viagogo.net\/v2\/events\/880821\/listingconstraints",
                        "title":null,
                        "templated":false
                    },
                    "event:listings":{
                        "href":"https:\/\/api.viagogo.net\/v2\/events\/880821\/listings?category_id=33700",
                        "title":"View Tickets",
                        "templated":false
                    },
                    "event:localwebpage":{
                        "href":"http:\/\/www.viagogo.it\/E-880821",
                        "title":null,
                        "templated":false
                    },
                    "event:webpage":{
                        "href":"http:\/\/www.viagogo.com\/ww\/E-880821",
                        "title":null,
                        "templated":false
                    }
                },
                "_embedded":{
                    "venue":{
                        "id":16001,
                        "name":"Fiera Milano",
                        "city":"Milano - Rho",
                        "latitude":45.5195,
                        "longitude":9.0869,
                        "_links":{
                            "self":{
                                "href":"https:\/\/api.viagogo.net\/v2\/venues\/16001",
                                "title":null,
                                "templated":false
                            }
                        },
                        "_embedded":{
                            "country":{
                                "code":"IT",
                                "name":"Italy",
                                "_links":{
                                    "self":{
                                        "href":"https:\/\/api.viagogo.net\/v2\/countries\/IT",
                                        "title":null,
                                        "templated":false
                                    }
                                }
                            }
                        }
                    }
                }
            },
            {
                "id":763260,
                "name":"NFL International Series 2015 - 3 Games Pack",
                "start_date":"2015-10-04T14:00:00+01:00",
                "end_date":"2015-11-01T23:30:00+00:00",
                "on_sale_date":"2014-12-19T16:44:00+00:00",
                "date_confirmed":true,
                "min_ticket_price":null,
                "notes_html":"<div class=\"v-box-pri v-in-18 v-padt-9 v-padb-12\">\n\t\n\t<ul class=\"ul mb0\">\n\t<li>All sales are final<\/li>\n\n<li>Age restrictions may apply, please check with the venue for more details<\/li>\n<li>Event dates and times are subject to change, it is up to you to check local listings for updates<\/li>\n<li>After your purchase, you will receive a confirmation email with your ticket delivery details and timing<\/li>\n\t<\/ul>\t\n<\/div>",
                "restrictions_html":null,
                "affiliate_commission_tier":"Normal",
                "_links":{
                    "self":{
                        "href":"https:\/\/api.viagogo.net\/v2\/events\/763260?category_id=4628",
                        "title":null,
                        "templated":false
                    },
                    "event:category":{
                        "href":"https:\/\/api.viagogo.net\/v2\/categories\/4628",
                        "title":null,
                        "templated":false
                    },
                    "event:listingconstraints":{
                        "href":"https:\/\/api.viagogo.net\/v2\/events\/763260\/listingconstraints",
                        "title":null,
                        "templated":false
                    },
                    "event:localwebpage":{
                        "href":"http:\/\/www.viagogo.co.uk\/E-763260",
                        "title":null,
                        "templated":false
                    },
                    "event:webpage":{
                        "href":"http:\/\/www.viagogo.com\/ww\/E-763260",
                        "title":null,
                        "templated":false
                    }
                },
                "_embedded":{
                    "venue":{
                        "id":468,
                        "name":"Wembley Stadium",
                        "city":"London",
                        "latitude":51.5567,
                        "longitude":-0.2831,
                        "_links":{
                            "self":{
                                "href":"https:\/\/api.viagogo.net\/v2\/venues\/468",
                                "title":null,
                                "templated":false
                            }
                        },
                        "_embedded":{
                            "country":{
                                "code":"GB",
                                "name":"United Kingdom",
                                "_links":{
                                    "self":{
                                        "href":"https:\/\/api.viagogo.net\/v2\/countries\/GB",
                                        "title":null,
                                        "templated":false
                                    }
                                }
                            }
                        }
                    }
                }
            },

can you explain how can i get list of event in specific venue?

**Comment by akilb** [comment]
Hey @VolodymyrMordas, thanks for pointing out this issue! There was a bug in the API where we weren't filtering events by venue correctly.

We've deployed a fix to the issue this morning so following the [`venue:events`](http://developer.viagogo.net/#venueevents) link on a `Venue` will now give you the correct set of events for that venue.

e.g. the URL request you gave (https://api.viagogo.net/v2/categories/0/events?venue_id=1364&page=2&page_size=1) now gives a result like:

```
{
  "total_items": 108,
  "page": 2,
  "page_size": 1,
  ...
}
```

Thanks!
